---
platform: linux

image_resource:
  type: docker-image
  source: {repository: alpine/git}

inputs:
- name: learning-concourse
- name: resource-gist

outputs:
- name: updated-gist

path:
  run: concourse-learning/basics/tasks/commit.sh