---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang}

inputs:
- name: learning-concourse
- name: urlsh

outputs:
- name: urlsh-bin

run:
  path: ./learning-concourse/basics/tasks/go-build.sh