---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
  - name: learning-concourse
  - name: some-data

run:
  path: learning-concourse/basics/tasks/read_file.sh