---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: learning-concourse

outputs:
- name: hello_file.txt

run:
  path: learning-concourse/basics/tasks/write_file.sh