---
resources:
- name: learning-concourse
  type: git
  source:
    uri: https://github.com/irbekrm/learning-concourse.git
- name: urlsh
  type: git
  source:
    uri: https://github.com/irbekrm/urlsh.git

jobs:
- name: unit-tests
  public: true
  plan:
  - get: learning-concourse
  - get: urlsh
  - task: unit-tests
    file: learning-concourse/basics/tasks/go-test.yml