---
resources:
- name: learning-concourse
  type: git
  source: 
    uri: https://github.com/irbekrm/learning-concourse.git
- name: resource-gist
  type: git
  source:
    uri: ((gist_uri))
    branch: master
    private_key: ((private_key))

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: learning-concourse
  - task: hello-world
    file: learning-concourse/basics/tasks/hello.yml
- name: task-inputs-outputs
  public: true
  plan:
  - get: learning-concourse
  - task: write-file
    file: learning-concourse/basics/tasks/write_file.yml
  - task: read-file
    file: learning-concourse/basics/tasks/read_file.yml
- name: publish-file
  public: true
  plan:
  - get: learning-concourse
  - get: resource-gist
  - task: publish-file
    file: learning-concourse/basics/tasks/commit.yml
  - put: resource-gist
    params: 
      repository: updated-gist
    
