---
resources:
- name: learning-concourse
  type: git
  source: https://github.com/irbekrm/learning-concourse.git

jobs:
  name: job-hello-world
  public: true
  plan:
  - get: learning-concourse
  - task: hello-world
    file: learning-concourse/basics/tasks/hello.yml

