---
resources:
- name: learning-concourse
  type: git
  source: 
    uri: https://github.com/irbekrm/learning-concourse.git

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: learning-concourse
  - task: hello-world
    file: learning-concourse/basics/tasks/hello.yml
- name: task-inputs-outputs
  public: true
  plan:
  - get: learning-concourse
  - task: write-file
    file: write_file.yml
  - task: read-file
    file: read_file.yml
    
